name: Docker Image WS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build and Push the Docker image 
        run: |
          docker build --tag anoniji/retrogile_ws:$(date +%s) ./podman/ws/.
          docker push anoniji/retrogile_ws:$(date +%s)
          docker build --tag anoniji/retrogile_ws:latest ./podman/ws/.
          docker push anoniji/retrogile_ws:latest
