name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build and Push the Docker image
        run: |
          docker build --tag anoniji/retrogile_api:latest ./podman/api/.
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:0.2.6
          docker push anoniji/retrogile_api:latest
