name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build the Docker image
        uses: actions/checkout@v4
      -
        name: Push the Docker image 
        run: |
          ls -alh
          docker build --tag anoniji/retrogile_api-api:$(date +%s) ./podman/api/.
          docker push anoniji/retrogile_api:latest
