name: Docker Image WS

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Tags
        id: tags
        run: |
          git fetch --tags

      - name: Auto minify the files
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: true

      - name: Build and Push the Docker image
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo ${latest_tag} > ./version
          docker build --tag anoniji/retrogile_ws:latest -f ./ws.Dockerfile .
          docker tag anoniji/retrogile_ws:latest anoniji/retrogile_ws:${latest_tag}
          docker push anoniji/retrogile_ws:${latest_tag}
          docker push anoniji/retrogile_ws:latest
