name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and Push the Docker image 
        uses: actions/checkout@v4
        with: 
          run: 
            docker build ./podman/api/. --file Dockerfile --tag my-image-name:$(date +%s)
            docker build --tag retrogile-api:$(date +%s) ./podman/api/.
            docker tag retrogile-api:$(date +%s) retrogile_api:latest
            docker push retrogile_api:latest
