name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build the Docker image
        uses: actions/checkout@v4
        with:
          run: docker build --tag retrogile-api:$(date +%s) ./podman/ws/.
      -
        name: Push the Docker image 
        run: |
          ls -alh
          docker tag retrogile-api:$(date +%s) retrogile_api:latest
          docker push retrogile_api:latest
