name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout Repository
        uses: actions/checkout@v4
      - 
        name: Get Tags
        id: tags
        run: |
          git fetch --tags       
      -
        name: Build and Push the Docker image
        run: |
          docker build --tag anoniji/retrogile_api:latest ./podman/api/.
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:$(git describe --abbrev=0 --tags)
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:$(git describe --abbrev=0 --tags)
          docker push anoniji/retrogile_api:latest
