name: Docker Image API

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Tags
        id: tags
        run: |
          git fetch --tags
      - name: Build and Push the Docker image
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          docker build --tag anoniji/retrogile_api:latest -f ./api.Dockerfile .
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:${latest_tag}
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:$(date +%s)
          docker push anoniji/retrogile_api:${latest_tag}
          docker push anoniji/retrogile_api:latest
