name: Docker Image API

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Tags
        id: tags
        run: |
          git fetch --tags

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          add_suffix: false
          inclusions: |-
            .*css.*
            .*pages.*
          exclusions: |-
            .*js.*

      - name: Build and Push the Docker image
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo ${latest_tag} > ./version
          docker build --tag anoniji/retrogile_api:latest -f ./api.Dockerfile .
          docker tag anoniji/retrogile_api:latest anoniji/retrogile_api:${latest_tag}
          docker push anoniji/retrogile_api:${latest_tag}
          docker push anoniji/retrogile_api:latest
