name: Docker Image API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Build & Push to Docker Hub
        uses: timzu/github-actions-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERFILE: "./podman/api/Dockerfile"
          IMAGE_NAME: "anoniji/retrogile_api"
          TAG_NAME: "v$(date +%s)"
          LATEST: "true"
